import bcrypt from 'bcryptjs'
const data = {
  users: [
    {
      name: 'Admin',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      role: "admin",
    },
    {
      name: 'User',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      role: "user",
    },
  ],
  playlist: [
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist1',
      slug: 'playlist-1',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-2',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-3',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-4',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-5',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-6',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-7',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-8',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-9',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-10',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-11',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-12',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-13',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-14',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-15',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
  ],
  products: [
      {
        
      user: '613f3c0b217785ee9b399d9c',
        name: 'Mysql Queries',
        slug: 'mysql-queries',
        category: 'Shirts',
        image: '/images/shirt3.jpg',
        price: 90,
        brand: 'Raymond',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'Mysql Queries',
      },
      {
        user: '613f3c0b217785ee9b399d9c',
        name: 'How to make a next app?',
        slug: 'create-next-app',
        category: 'Pants',
        image: '/images/pants1.jpg',
        price: 90,
        brand: 'Oliver',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'How to make a next app?',
      },
      {
        user: '613f3c0b217785ee9b399d9c',
        name: 'How to make a react app?',
        slug: 'create-react-app',
        category: 'Pants',
        image: '/images/pants2.jpg',
        price: 95,
        brand: 'Zara',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'How to make a react app?',
      },
      {
        user: '613f3c0b217785ee9b399d9c',
        name: 'what is web development?',
        slug: 'what-is-web-development',
        category: 'Pants',
        image: '/images/pants3.jpg',
        price: 75,
        brand: 'Casely',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'what is web development?',
      },
      {
        user: '613f3c0b217785ee9b399d9c',
        name: 'How to connect a database?',
        slug: 'connect a database',
        category: 'Pants',
        image: '/images/pants3.jpg',
        price: 75,
        brand: 'Casely',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'How to connect a database?',
      },
      {
        user: '613f3c0b217785ee9b399d9c',
        name: 'How to create a responsive website?',
        slug: 'responsive-web-development',
        category: 'Pants',
        image: '/images/pants3.jpg',
        price: 75,
        brand: 'Casely',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'How to create a responsive website?',
      },
  ],
    categories: [

      {
        name: 'HTML & CSS',
        slug: 'html-css',
        image: 'https://res.cloudinary.com/masterdevs/image/upload/v1639856155/codeaddon/3_uwf0hd.jpg',
        description: 'HTML & CSS',
        type:"article"
      },
      {
        name: 'PHP & MYSQL',
        slug: 'php-mysql',
        image: 'https://res.cloudinary.com/masterdevs/image/upload/v1640231976/codeaddon/codeaddon-image-icon2_srky38.jpg',
        description: 'PHP & MYSQL',
        type:"video"
      },
      {
        name: 'Javascript',
        slug: 'javascript',
        image: 'https://res.cloudinary.com/masterdevs/image/upload/v1640231976/codeaddon/codeaddon-image-icon2_srky38.jpg',
        description: 'Javascript',
        type:"video"
      },
      {
        name: 'Reactjs',
        slug: 'reactjs',
        image: 'https://res.cloudinary.com/masterdevs/image/upload/v1640231976/codeaddon/codeaddon-image-icon2_srky38.jpg',
        description: 'Reactjs',
        type:"video"
      },
      {
        name: 'Nextjs',
        slug: 'nextjs',
        image: 'https://res.cloudinary.com/masterdevs/image/upload/v1640231976/codeaddon/codeaddon-image-icon2_srky38.jpg',
        description: 'Nextjs',
        type:"video"
      },
      {
        name: 'PHP',
        slug: 'php',
        image: 'https://res.cloudinary.com/masterdevs/image/upload/v1640231976/codeaddon/codeaddon-image-icon2_srky38.jpg',
        description: 'PHP',
        type:"article"
      },
      {
        name: 'MYSQL',
        slug: 'mysql',
        image: 'https://res.cloudinary.com/masterdevs/image/upload/v1640231976/codeaddon/codeaddon-image-icon2_srky38.jpg',
        description: 'MYSQL',
        type:"video"
      },
      {
        name: 'HTML',
        slug: 'html',
        image: 'https://res.cloudinary.com/masterdevs/image/upload/v1640231976/codeaddon/codeaddon-image-icon2_srky38.jpg',
        description: 'HTML',
        type:"video"
      },

    ]
}
export default data
