const data = {
    products: [

      {
        name: 'Mysql Queries',
        slug: 'mysql-queries',
        category: 'Shirts',
        image: '/images/shirt3.jpg',
        price: 90,
        brand: 'Raymond',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'Mysql Queries',
      },
      {
        name: 'How to make a next app?',
        slug: 'create-next-app',
        category: 'Pants',
        image: '/images/pants1.jpg',
        price: 90,
        brand: 'Oliver',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'How to make a next app?',
      },
      {
        name: 'How to make a react app?',
        slug: 'create-react-app',
        category: 'Pants',
        image: '/images/pants2.jpg',
        price: 95,
        brand: 'Zara',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'How to make a react app?',
      },
      {
        name: 'what is web development?',
        slug: 'what-is-web-development',
        category: 'Pants',
        image: '/images/pants3.jpg',
        price: 75,
        brand: 'Casely',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'what is web development?',
      },
    ],
  };
  export default data;